<a href="https://colab.research.google.com/github/HoHoangQuan/THtoancaocap/blob/main/Baitapchuong5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TH1

In [ ]:
x = 3  
print  (x) 

3


In [ ]:
import math 
x = math.sqrt(1+x)
print (x) 

2.0


In [ ]:
x = math.sqrt(1+x) 
print (x) 

1.7320508075688772


In [ ]:
x = math.sqrt(1+x) 
print (x)

1.6528916502810695


TH2

In [ ]:
x = 3 
lap = 1 
while (x != math.sqrt(x+1)):
  x = math.sqrt(x+1) 
  lap = lap  +1   
  print(x)

2.0
1.7320508075688772
1.6528916502810695
1.6287699807772333
1.621348198499395
1.6190578119694785
1.618350336598809
1.6181317426584303
1.618064196086926
1.6180433233034663
1.6180368732830122
1.6180348801194033
1.6180342641981977
1.6180340738680992
1.6180340150528663
1.61803399687796
1.618033991261605
1.6180339895260558
1.6180339889897417
1.6180339888240116
1.6180339887727981
1.6180339887569724
1.6180339887520818
1.6180339887505706
1.6180339887501036
1.6180339887499593
1.6180339887499147
1.618033988749901
1.6180339887498967
1.6180339887498953
1.618033988749895


In [ ]:
print(lap)

32


TH3

In [ ]:
import sympy as sp 
from sympy import Symbol 
x = Symbol('x') 
sp.solve(x-sp.sqrt(1+x),x) 

[1/2 + sqrt(5)/2]

TH4

In [ ]:
import numpy as np 
v1 = np.array([1., 2., 3.])
v2 = np.array([2., 1., 0.]) 
v3 = v1 + v2
v3 

array([3., 3., 3.])

In [ ]:
3*v1  + 2*v2 

array([7., 8., 9.])

In [ ]:
[1, 2, 3] + [2, 1, 0] 

[1, 2, 3, 2, 1, 0]

In [ ]:
3*[1, 2, 3] + 2*[2, 1, 0] 

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

In [ ]:
 v4 = np.hstack([v1, v2]) 

In [ ]:
np.dot(v1, v2) 

4.0

In [ ]:
angles = np.linspace(0, np.pi/2, 5) 
print(angles )

[0.         0.39269908 0.78539816 1.17809725 1.57079633]


In [ ]:
np.sin(angles) 

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

In [ ]:
import sympy as sy 
sy.sin(angles) 

AttributeError: ignored

In [4]:
import numpy as np 
from sympy import sin as sysin 
angles = np.linspace(0, np.pi/2, 5) 
sinangle = np.zeros(5) 
len(angles)
for i in range(len(angles)): 
  sinangle[i] = sysin(angles[i]) 
sinangle    

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

TH5

In [5]:
import numpy as np 
goc = np.pi/3
A = np.array([ [np.cos(goc), -np.sin(goc)],   
              [np.sin(goc),  np.cos(goc)] ]) 
V = np.array([1. , 0. ]) 
Y = np.dot(A, V) 
Y 

array([0.5      , 0.8660254])

TH6

In [6]:
from numpy import diff 
dx = 0.1 
y = [1, 2, 3, 4, 4, 5, 6] 
dy = diff(y)/dx 
dy 

array([10., 10., 10.,  0., 10., 10.])

In [7]:
z = np.array([1, 2, 3, 4, 4, 5, 6]) 
dz = diff(z)/dx 
dz 

array([10., 10., 10.,  0., 10., 10.])

In [8]:
from numpy import diff 
x = [.1, .2, .5, .6, .7, .8, .9] 
y = [1, 2, 3, 4, 4, 5, 6] 
 dydx = diff(y)/diff(x) 
 print (dydx) 

IndentationError: ignored