<a href="https://colab.research.google.com/github/HoHoangQuan/THtoancaocap/blob/main/KTgiuakylan2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BAI 1

In [ ]:
trang_thai = "s0"
def chuyen(tin_hieu):
  global trang_thai 
  if trang_thai =="s0":
    if tin_hieu == 1:
      print("1 - s0")
      trang_thai ="s0"
    elif tin_hieu ==0: 
      print("0 - s1")
      trang_thai = "s1"
  elif trang_thai =="s1": 
    if tin_hieu == 1 :
      print("1 - s1")
      trang_thai = "s1"
    elif tin_hieu ==0: 
      print("1 -s2")
      trang_thai = "s2"
  elif trang_thai =="s2":
    if tin_hieu==1:
      print("1-s2")
      trang_thai="s2"
    elif tin_hieu ==0:
      print("0 - s0")
      trang_thai ="s0"

In [ ]:
tap_tinhieu = [1,0,1,0,1,0]  
for i in tap_tinhieu:
 chuyen(i)

1 - s0
0 - s1
1 - s1
1 -s2
1-s2
0 - s0


BAI 2

In [ ]:
import math
import sys
class Graph():
  def __init__(cung, dinh):
    cung.x = dinh
    cung.graph = [[0 for column in range(dinh)]
                  for row in range(dinh)]
  def inketqua(cung, L, a):
    print ("đỉnh nguồn xuất phát từ: ")
    for nut in range(cung.x):
      print (a," đến đỉnh ",nut, "độ dài đường đi là: ", L[nut])
  def duongdinhonhat(cung, L, P):
    min = sys.maxsize
    for x in range(cung.x):
      if L[x] < min and P[x] == False:
        min = L[x]
        min_index = x
    return min_index
  def timduongdi(cung, a):
    L = [sys.maxsize] * cung.x
    L[a] = 0
    P = [False] * cung.x
    for cout in range(cung.x):
      u = cung.duongdinhonhat(L, P)
      P[u] = True
      for x in range(cung.x):
        if cung.graph[u][x]>0 and P[x]== False and L[x] > L[u] + cung.graph[u][x]:
          L[x]=L[u] + cung.graph[u][x]
    cung.inketqua(L,a)

In [ ]:
g = Graph(6)

In [24]:
g.graph = [[0, 4, 0, 1, 0, 0],
[0, 0, 8, 0, 0, 0],
[0, 0, 0, 0, 0, 4],
[0, 0, 9, 0, 5, 0],
[0, 0, 1, 0, 0, 7],
[0, 0, 0, 0, 0, 0]
];
g.timduongdi(0);

đỉnh nguồn xuất phát từ: 
0  đến đỉnh  0 độ dài đường đi là:  0
0  đến đỉnh  1 độ dài đường đi là:  4
0  đến đỉnh  2 độ dài đường đi là:  7
0  đến đỉnh  3 độ dài đường đi là:  1
0  đến đỉnh  4 độ dài đường đi là:  6
0  đến đỉnh  5 độ dài đường đi là:  11


BAI 3

In [ ]:
import networkx as nx
g = nx.Graph()
g.add_node('TP.HCM')
g.add_node('Dong Nai')
g.add_node('Ba Ria Vung Tau')
g.add_node('Lam Dong')
g.add_node('Can Tho')
g.add_node('Long An')
g.add_edge('TP.HCM', 'Dong Nai')
g.add_edge('TP.HCM', 'Ba Ria Vung Tau')
g.add_edge('TP.HCM', 'Long An')
g.add_edge('Dong Nai', 'Lam Dong')
g.add_edge('Dong Nai', 'Ba Ria Vung Tau')
nx.shortest_path(g, 'Lam Dong', 'Long An')

['Lam Dong', 'Dong Nai', 'TP.HCM', 'Long An']

BAI 4

In [ ]:
import math 
import numpy as np

In [ ]:
def tinh_huong(dem,m_dong,n_cot,vitri):
  huong=np.zeros((m_dong,n_cot))
  for dong in range(m_dong):
    for cot in range(n_cot):
      xx,yy,mymax=0,0,0
      for i in range(-1,2):
        for j in range(-1,2):
          if(i*i+j>0)and\
           (dong+i>=0) and (dong+i<m_dong) and \
           (cot+j>=0)and(cot+j<n_cot)and\
      (mymax*math.sqrt(i*i+j)<dem[dong][cot]-dem[dong+i][cot+j]):
              mymax=dem[dong][cot]-dem[dong+i][cot+j]
              xx=i
              yy=j
      huong[dong][cot]=vitri[xx+1][yy+1]
  return huong 

def tinh_tichluy(p,q,m_dong,n_cot):
  for i in range(-1,2):
    for j in range(-1,2):
      if(i*i+j*j>0)and\
      (p+i>=0) and (p+i<m_dong)and\
      (q+j>=0) and (q+j<n_cot)and\
      (huong[p+i][q+j]==vitri[-(i-1)][-(j-1)]):
          t1.append(1)
          tinh_tichluy(p+i,q+j,m_dong,n_cot)
  return len(t1)
vitri=np.array([[32,64,128],[16,0,1],[8,4,2]])
dem = np.array([ [78,72,69,71,58,49], 
                 [74,67,56,49,46,50], 
                 [69,53,44,37,38,48], 
                 [64,58,55,22,31,24], 
                 [68,61,47,21,16,19], 
                 [74,53,34,12,11,12] ]) 
m_dong = dem.shape[0] #6 
n_cot = dem.shape[1] #6 
tichluy = np.zeros((m_dong, n_cot)) #[ [0 for j in range(n_cot)] for i in range(m_dong)] 
huong = tinh_huong(dem, 6,6, vitri) 
for i in range(m_dong): 
 for j in range(n_cot): 
  t1 = [] 
  tichluy[i][j] = tinh_tichluy(i, j, m_dong, n_cot) 
print (dem) 
print (huong) 
print (tichluy)


[[78 72 69 71 58 49]
 [74 67 56 49 46 50]
 [69 53 44 37 38 48]
 [64 58 55 22 31 24]
 [68 61 47 21 16 19]
 [74 53 34 12 11 12]]
[[  2.   2.   2.   4.   4.   0.]
 [  2.   2.   2.   4.   4.   4.]
 [  1.   1.   2.   4.   2.   4.]
 [128. 128.   1.   2.   4.   4.]
 [  2.   2.   1.   4.   4.   4.]
 [  1.   1.   1.   1.   0.   0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  2.  1.  0.]
 [ 0.  3.  7.  5.  2.  1.]
 [ 0.  0.  0. 15.  0.  5.]
 [ 0.  0.  0.  1. 17.  6.]
 [ 0.  2.  4.  7. 26.  7.]]
